language: node_js

cache:
    yarn: true

node_js:
    - '11'
    - '10'

branches:
    only:
        - master
        - develop

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install:
    - yarn

script:
    - yarn lint
    - yarn test

after_success:
    - ./node_modules/.bin/codecov -f coverage/*.json

notifications:
    webhooks: https://hook.bearychat.com/=bw6u8/travis/865e3593ff855a09fd197bab9e5a37a4
