name: CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['10', '12']

        name: Node ${{ matrix.node }} test

        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install -g yarn
            - name: Run yarn install, test
              run: |
                  yarn install
                  yarn test
